gridmap_to_polygon_converter:
    ros__parameters:
      map_topic: "/map"
      use_file_input: true
      map_yaml_path: "/home/nguyen/convert_polygon/src/gridmap_to_polygon/maps/map_03.yaml"
      map_pgm_path: "/home/nguyen/convert_polygon/src/gridmap_to_polygon/maps/map_03.pgm"
      occupancy_threshold: 50
      min_polygon_area: 2.0
      simplify_tolerance: 2.0
      min_area: 100
      publish_frame_id: "map"